feat: Sites & Applications UX fixes
USSF-ORBIT/ussf-portal-client pull request #293
Opened 2021-10-25 22:18 UTC by suzubara

## Description 

This PR makes some small UX/design fixes as described in #286 (everything listed in the **COMPLETED** section). It does _not_ cover the items contained in separate issues.

- [x] Adjust MySpace columns to 3, maybe adjust margins/padding
- [x] Change color on search dropdown text to white 
- [x] Change padding on collections boxes (24px for top/bottom and 16pc for L/R)
- [x] Even out padding within myspace container (24px on all sides)
- [x] Remove side nav links that are unused (My profile, Subordinate profiles, etc...)
- [x] Change all footer text to white
- [x] Add hover states to buttons
- [x] Remove hover state for search dropdown
- [x] "Add section" box height should be equal to a collection card with 5 links inside it
- [x] "Search" text is not using trebuchet
- [x] In "alphabetical" view, description columns will need to be moved to the left to make room for more content (Note: this might actually be resolved on it's own once content is added)
- [x] Add hover states to main nav
- [x] Update button styles on alphabetical/type sorts
- [x] ReactUSWDS ComboBox scroll bug (https://github.com/trussworks/react-uswds/issues/1693)

Fixes #286 

## Review Notes

Review the deployed app & Storybook against the list of UX fixes above and verify that they are in fact completed.

2021-10-29 22:12 UTC, jbecker01 approved these changes
From what I could check, it looks good!
 

- [x] Adjust MySpace columns to 3, maybe adjust margins/padding
- [ ]  Change color on search dropdown text to white
- [ ]  Change padding on collections boxes (24px for top/bottom and 16pc for L/R)
- [x]  Even out padding within myspace container (24px on all sides)
- [x]  Remove side nav links that are unused (My profile, Subordinate profiles, etc...)
- [x]  Change all footer text to white
- [x]  Add hover states to buttons
- [x]  Remove hover state for search dropdown
- [x]  "Add section" box height should be equal to a collection card with 5 links inside it
- [ ]  "Search" text is not using trebuchet
- [ ]  In "alphabetical" view, description columns will need to be moved to the left to make room for more content (Note: this might actually be resolved on it's own once content is added)
- [x]  Add hover states to main nav
- [x]  Update button styles on alphabetical/type sorts
- [x]  ReactUSWDS ComboBox scroll bug ([fix] ComboBox scroll behavior trussworks/react-uswds#1693)

2021-11-01 18:00 UTC, malworks requested changes
For the "Change search dropdown text to white" bullet, can we also change the dropdown icon to white?
<img width="249" alt="Screen Shot 2021-11-01 at 10 52 50 AM" src="https://user-images.githubusercontent.com/20548582/139717597-aea12b6c-2392-424b-9ceb-28a1fac1c118.png">
I took a quick look to change this myself but couldn't find the icon for some reason?

2021-11-01 19:32 UTC, malworks approved these changes

2021-11-01 19:47 UTC, abbyoung approved these changes

2021-11-01 19:58 UTC, merged