Sc 543/documents page
USSF-ORBIT/ussf-portal-client pull request #860
Opened 2022-11-10 22:27 UTC by jcbcapps

# SC-###

## Proposed changes

---

## Reviewer notes

## Setup

---

## Code review steps

### As the original developer, I have

- [ ] Met the acceptance criteria, or will meet them in subsequent PRs or stories
  - ... 
- [ ] Created new stories in Storybook if applicable
  - [ ] Checked that all Storybook accessibility checks are passing
- [ ] Created/modified automated unit tests in Jest
  - [ ] Including jest-axe checks when UI changes
- [ ] Created/modified automated E2E tests in Cypress
  - [ ] Including cypress-axe checks when UI changes
  - [ ] Checked that the E2E test build is not failing
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.md):
  - [ ] Checked responsiveness in mobile, tablet, and desktop
  - [ ] Checked keyboard navigability
  - [ ] Tested with [VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) in Safari
  - [ ] Checked VO's [rotor menu](https://github.com/trussworks/accessibility/blob/master/README.md#how-to-use-the-rotor-menu) for landmarks, page heading structure and links
  - [ ] Used a browser a11y tool to check for issues (WAVE, axe, ANDI or Accessibility addon tab for Storybook)
- [ ] Requested a design review for user-facing changes
- For any new migrations/schema changes:
  - [ ] Followed guidelines for zero-downtime deploys

### As code reviewer(s), I have

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
  - [ ] Checked that the E2E test build is not failing
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] Considered marking this as accepted even if there are small changes needed
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.md):
  - [ ] Checked responsiveness in mobile, tablet, and desktop
  - [ ] Checked keyboard navigability
  - [ ] Tested with [VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) in Safari
  - [ ] Checked VO's [rotor menu](https://github.com/trussworks/accessibility/blob/master/README.md#how-to-use-the-rotor-menu) for landmarks, page heading structure and links
  - [ ] Used a browser a11y tool to check for issues (WAVE, axe, ANDI or Accessibility addon tab for Storybook)

### As a designer reviewer, I have

- [ ] Checked in the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.md):
  - [ ] Checked responsiveness in mobile, tablet, and desktop
  - [ ] Checked keyboard navigability
  - [ ] Tested with [VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) in Safari
  - [ ] Checked VO's [rotor menu](https://github.com/trussworks/accessibility/blob/master/README.md#how-to-use-the-rotor-menu) for landmarks, page heading structure and links
  - [ ] Used a browser a11y tool to check for issues (WAVE, axe, ANDI or Accessibility addon tab for Storybook)

### As a test user, I have

- Run through the [Test Script](hhttps://docs.google.com/spreadsheets/d/1eV8UK0aJZ0qrzjnXf5SJ_uRiV7bpsj3yrhRFEkjOvV4/edit?usp=sharing):
  - [ ] On commercial internet in IE11
  - [ ] On commercial internet in Firefox
  - [ ] On commercial internet in Chrome
  - [ ] On commercial internet in Safari
  - [ ] On NIPR in IE11
  - [ ] On NIPR in Firefox
  - [ ] On NIPR in Chrome
  - [ ] On NIPR in Safari
  - [ ] On a mobile device in Firefox
  - [ ] On a mobile device in Chrome
  - [ ] On a mobile device in Safari
- [ ] Added any anomalous behavior to this PR

---

## Screenshots

2022-11-14 23:29 UTC, jbecker01 commented
I noticed on Light Mode, the toggle button color is #243593 instead of #82CC92

<img width="533" alt="Screen Shot 2022-11-14 at 3 27 46 PM" src="https://user-images.githubusercontent.com/52676444/201789323-53def201-bbc2-400c-8473-5ce4be054d91.png">

<img width="520" alt="Screen Shot 2022-11-14 at 3 27 55 PM" src="https://user-images.githubusercontent.com/52676444/201789336-38dc7e9c-5564-4cb9-a25c-4c6fc11d6937.png">

2022-11-16 17:10 UTC, malworks requested changes
Hi! Looks great in light and dark mode. A couple things:

- The accordion headers ("Essential Reading") are using h3's, when they should be using the label tag. 
<img width="516" alt="image" src="https://user-images.githubusercontent.com/20548582/202246430-785d87f8-93ac-4832-ae6f-4015e0624a65.png">

- Question: The design breaks at more narrow tablet/mobile widths but I'm not sure we're "officially" supporting mobile or not. Are we?
- Figma has the document type icon listed in front of each document. Is this in scope? (See photo below) 

<img width="328" alt="image" src="https://user-images.githubusercontent.com/20548582/202246982-c7e31433-b65f-45e2-a970-c8ab1b236b1d.png">

2022-11-16 22:44 UTC, gidjin approved these changes
Minor note about the test structure in the new test file, but I don't see a need to block the PR on that. Approving from an eng stand point, please follow up with Mallory on the notes she left.

Question: Should the `Essential Reading` section be expanded by default since it's the only one? Might be a good question for @malworks or @shkeating

2022-11-16 22:44 UTC, gidjin commented on src/__tests__/pages/ussf-documentation.test.tsx
> +    })
Thought, is there a reason to continue this pattern of sharing `html`. IIRC the recommendation is to not do that now with react-testing-library. I think this was the article: https://kentcdodds.com/blog/avoid-nesting-when-youre-testing

Suggestion: refactor this to call render in each it block or just combine them all into one test. I can't find the article that recommended that but I read one from Kent Dodds about that.

2022-11-17 22:07 UTC, jcbcapps commented
> Hi! Looks great in light and dark mode. A couple things:
> 
> * The accordion headers ("Essential Reading") are using h3's, when they should be using the label tag.
> 
> * Question: The design breaks at more narrow tablet/mobile widths but I'm not sure we're "officially" supporting mobile or not. Are we?
> * Figma has the document type icon listed in front of each document. Is this in scope? (See photo below)
> 
@malworks 
1) Good catch on the h3's, I'll make that change.
2) We don't currently support mobile and, as far as I know, we have no concrete plans to do so.
3) I skipped this for now because we're still working on the file upload functionality. I plan to write a chore in Shortcut to loop back and move these files to the CMS after we get file upload done.

2022-11-18 15:02 UTC, jcbcapps commented
@malworks I spoke too soon on changing the h3 in the Accordion. Guess I should have mentioned that the Accordion component is a ReactUSWDS component, and it uses a `headingLevel` prop for each item that is required. So I can't make that change, but it doesn't seem crucial to me. Any thoughts? 

Also, @gidjin had a great question above asking if the 'Essential Reading' section should be open by default since it is the only Accordion item. I went ahead and made that change so that you could see what it would look like, but let me know if I need to change it back!

2022-11-18 17:21 UTC, malworks commented
> @malworks I spoke too soon on changing the h3 in the Accordion. Guess I should have mentioned that the Accordion component is a ReactUSWDS component, and it uses a `headingLevel` prop for each item that is required. So I can't make that change, but it doesn't seem crucial to me. Any thoughts?
> 
> Also, @gidjin had a great question above asking if the 'Essential Reading' section should be open by default since it is the only Accordion item. I went ahead and made that change so that you could see what it would look like, but let me know if I need to change it back!

No worries, it's fine as is. And nice addition to keep the 'Essential Reading' open by default!

2022-11-18 17:21 UTC, malworks approved these changes

2022-11-18 20:00 UTC, merged